---
- name: "Install Nginx and Upload my Web Page"
  hosts: all 
  become: yes
  tasks:
    - name: "Debug"
      ansible.builtin.debug:
        msg: "Test debug2"

    - name: "Copy website files"
      host synchronize:
        src: ./
        dest: /var/www/vladyslavdubov.site


