---
- name: "Install Nginx and Upload my Web Page"
  hosts: all 
  become: yes
  tasks:
    - name: "Debug"
      ansible.builtin.debug:
        msg: "Test debug"

    - name: "Update apt cache and install Nginx"
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: "Copy website files"
      copy:
        src: ./
        dest: /var/www/vladyslavdubov.site
        mode: preserve

    - name: "Apply Nginx config"
      copy:
        src: ./vladysalvdubov.site.conf
        dest: /etc/nginx/sites-available/
      notify: Restart Nginx

    - name: "Enable new site"
      file:
        src: /etc/nginx/sites-available/vladysalvdubov.site.conf
        dest: /etc/nginx/sites-enabled/vladysalvdubov.site.conf
        state: link
      notify: Restart Nginx

    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted 

